import { GoogleGenAI } from "@google/genai";
import {
  CacheType,
  ChatInputCommandInteraction,
  MessageFlags,
  SlashCommandBuilder,
} from "discord.js";

export const name = "comeback";
export const builder = new SlashCommandBuilder()
  .setName(name)
  .setDescription("Get a comeback message based on the context you provide")
  .addStringOption((option) =>
    option
      .setName("message_id")
      .setDescription("The ID of the message to generate a comeback for")
      .setRequired(true)
  )
  .addStringOption((option) =>
    option
      .setName("context")
      .setDescription("The context to build up the comeback from")
      .setRequired(false)
      .setMinLength(10)
  )
  .addBooleanOption((option) =>
    option.setName("anonymous").setDescription("Send the comeback anonymously")
  );

const ai = new GoogleGenAI({});

export default async (interaction: ChatInputCommandInteraction<CacheType>) => {
  const messageID = interaction.options.getString("message_id", true).trim();
  const context = interaction.options.getString("context")?.trim() || "";
  const anonymous = interaction.options.getBoolean("anonymous") || false;

  await interaction.deferReply({
    flags: MessageFlags.Ephemeral,
  });

  const messageChannel = await interaction.client.channels
    .fetch(interaction.channelId)
    .catch(() => null);

  if (!messageChannel || !messageChannel.isTextBased()) {
    await interaction.editReply({
      content: "Either I lack permissions or not in the server.",
    });
    return;
  }

  const message = await messageChannel.messages
    .fetch(messageID)
    .catch(() => null);

  if (!message) {
    await interaction.editReply({
      content: "Are you sure that ID exists? *suspects*",
    });
    return;
  }

  const comeback = await ai.models.generateContent({
    model: "gemini-2.5-flash-lite-preview-06-17",
    contents:
      `${message.author.displayName} said "${message.content}".` +
      (context ? ` There's some context provided by the user: ${context}` : ""),
    config: {
      systemInstruction: `You are a sarcastic Gen-Z roastmaster who lives online and never misses a chance to clap back.

Given a roast, insult, or sassy comment, respond with a short and savage **comeback**. Keep it clever, biting, and modern — like something you'd hear in a TikTok comment war, Discord thread, or viral quote tweet.

Keep your response to **one line**. Use internet slang, irony, and Gen-Z humor. Be creative, but not edgy/offensive. It should feel like a mic drop, not an actual fight.

Occasionally include rare or chaotic energy replies like:
- "Sorry, I don’t argue with NPCs."
- "Bold of you to speak when autocorrect still can’t fix your personality."
- "That comeback had the structural integrity of a soggy biscuit."

Never explain or apologize. Just drop the line and go. Output only the comeback line, nothing else. Look more involved with the chat and don't look out of the box`,
      temperature: 0.5,
    },
  });

  await message.reply({
    content:
      comeback.text +
      (anonymous ? "" : `\n\n-# Comeback generated by ${interaction.user}`),
    allowedMentions: {
      users: [],
      roles: [],
    },
  });

  await interaction.editReply({
    content: "Comeback sent successfully!",
  });
};
