import { Command } from "#lib/command";
import { generateButtonId, parseButtonId } from "#utils/buttonId";
import { GoogleGenAI } from "@google/genai";
import {
  ActionRowBuilder,
  ButtonBuilder,
  ButtonInteraction,
  ButtonStyle,
  CacheType,
  ChatInputCommandInteraction,
  EmbedBuilder,
  SlashCommandBuilder,
} from "discord.js";

const name = "truth-n-dare";
const ai = new GoogleGenAI({});

export default class extends Command {
  public static override commandName = name;
  public static override development = true;

  public static override builder() {
    return new SlashCommandBuilder()
      .setName(name)
      .setDescription("Play a quick game of Truth or Dare");
  }

  public static override async chatInputRun(
    interaction: ChatInputCommandInteraction<CacheType>
  ) {
    await interaction.reply({
      embeds: [
        new EmbedBuilder()
          .setTitle("Truth or Dare")
          .setDescription(
            "You summoned the Truth and Dare master, now it's time to choose your fate!"
          )
          .setColor("Random")
          .setFooter({ text: "Click a button to choose!" }),
      ],
      components: [
        new ActionRowBuilder<ButtonBuilder>().addComponents([
          new ButtonBuilder()
            .setLabel("Truth")
            .setCustomId(generateButtonId(name, "truth"))
            .setStyle(ButtonStyle.Primary)
            .setEmoji("🗣️"),
          new ButtonBuilder()
            .setLabel("Dare")
            .setCustomId(generateButtonId(name, "dare"))
            .setStyle(ButtonStyle.Primary)
            .setEmoji("💪"),
        ]),
      ],
    });
  }

  public static override async buttonRun(interaction: ButtonInteraction) {
    switch (parseButtonId(interaction.customId).customId) {
      case "truth":
        await interaction.deferReply();

        const truth = await ai.models.generateContent({
          model: "gemini-2.5-flash-lite-preview-06-17",
          contents:
            "Generate a random truth question for a game of Truth or Dare.",
          config: {
            systemInstruction:
              "You are a game master for Truth or Dare. Generate a random truth questions/dares that are silly, funny, spicy, doable and suitable for a audience sitting on discord. The question should be thought-provoking but not too personal. Keep in mind you are catering a Gen Z. Don't talk about TikTok, might refer Instagram if you really need to.",
          },
        });

        await interaction.editReply({
          content:
            truth.text +
            "\n\n-# Content is generated by AI, bot/developers isn't accountable for any content. ",
        });
        break;

      case "dare":
        await interaction.deferReply();

        const dare = await ai.models.generateContent({
          model: "gemini-2.5-flash-lite-preview-06-17",
          contents: "Generate a random dare for a game of Truth or Dare.",
          config: {
            systemInstruction:
              "You are a game master for Truth or Dare. Generate a random truth questions/dares that are silly, funny, spicy, doable and suitable for a audience sitting on discord. The question should be thought-provoking but not too personal. Keep in mind you are catering a Gen Z. Don't talk about TikTok, might refer Instagram if you really need to. Don't ask people to dance or act",
          },
        });

        await interaction.editReply({
          content:
            dare.text +
            "\n\n-# Content is generated by AI, bot/developers isn't accountable for any content. ",
        });
        break;
    }
  }
}
